### ISSUE TITLE
change directory structure

### ISSUE THREAD

**Issue by Anupam-dagar** [opencode18/CodeStash#44]
the directory structure needs to be changed.
Make a new folder Questions and move readme from day 1 and day 2 in it.
Before moving the readme, rename them to day1.md and day2.md respectively.

The way submissions are done needs to be changed.
In solutions folder create a folder for each username whose code is their and shift codes in respective folders.

Finally after doing this change the readme on how to add solution.

**Comment by Ace-Bansal** [comment]
I'll do it

**Comment by adiagg2000** [comment]
Can i do this?

**Comment by Anupam-dagar** [comment]
assigned to @Ace-Bansal

**Comment by aswinzz** [comment]
@Ace-Bansal  can u move the new files too

**Comment by Ace-Bansal** [comment]
@aswinzz Sure :)
