### ISSUE TITLE
Do the same question in Go 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/CodeStash#52]
implement the same code in Go and send pr to https://github.com/gostudent/Letsgo

First pr gets 30 points.
others get 10 and wont be merged.

**Comment by namantw** [comment]
Day 1 ques or Day 2 please clarify

**Comment by gauthamzz** [comment]
everyday . the same question

**Comment by surasnayak** [comment]
sending a pr with the link is enough for the solution in go?

**Comment by aswinzz** [comment]
Make the pr here and  letsgo repo too

**Comment by marshallKR7** [comment]
@aswinzz  As said by @gauthamzz, don't we have to make a blog?

**Comment by surasnayak** [comment]
@aswinzz done both. Please check.
