### ISSUE TITLE
Star This Repo

### ISSUE THREAD

**Issue by mubaris** [opencode18/CodeStash#55]
Post Screenshot

**Comment by Re42** [comment]
![image](https://user-images.githubusercontent.com/33805964/34839039-44f2edba-f726-11e7-8cb8-d18774127bdd.png)

**Comment by 16priyesh** [comment]
![image](https://user-images.githubusercontent.com/28901008/34839205-cb9bf0be-f726-11e7-987d-c267795aa67d.png)

**Comment by ananya-agrawal** [comment]
![a](https://user-images.githubusercontent.com/33188930/34839310-3512bba4-f727-11e7-8c3a-d365e5deed53.png)

**Comment by GOVINDDIXIT** [comment]
![capturec](https://user-images.githubusercontent.com/32304546/34839360-6026b462-f727-11e7-8872-5c8cc3325977.PNG)

**Comment by AK-007** [comment]
![screenshot 54](https://user-images.githubusercontent.com/26346816/34839631-508adf00-f728-11e7-8582-c3aff1bac388.png)

**Comment by brain-sick** [comment]
![1](https://user-images.githubusercontent.com/34164978/34839655-6a307fc8-f728-11e7-8a85-c0f3caded4f3.png)

**Comment by AbhiTaker** [comment]
![screenshot 88](https://user-images.githubusercontent.com/25261313/34840405-ee53120a-f72a-11e7-8431-cd4d1909af8a.png)

**Comment by poor-kid** [comment]
![screenshot-2018-1-11 opencode18 codestash](https://user-images.githubusercontent.com/16176277/34840554-55d0b644-f72b-11e7-9faa-a2e96022366c.png)

**Comment by namantw** [comment]
![image](https://user-images.githubusercontent.com/31323328/34840652-a80e91a6-f72b-11e7-8b0e-604cc31ba4d0.png)

**Comment by rahulkumaran** [comment]
![screenshot from 2018-01-12 00-07-10](https://user-images.githubusercontent.com/26206171/34840928-91e15836-f72c-11e7-938b-74dfe01ce9f5.png)

**Comment by nikki1016** [comment]
![star](https://user-images.githubusercontent.com/26041681/34841095-14d97002-f72d-11e7-82ff-fb35e317ad7d.png)

**Comment by ShiningSaurabh** [comment]
![capture](https://user-images.githubusercontent.com/34839782/34841140-3e778bf6-f72d-11e7-8790-73c118ebf065.PNG)

**Comment by maverick0004** [comment]
![screenshot 13](https://user-images.githubusercontent.com/33194760/34841256-a8e1e770-f72d-11e7-8a1c-b72b04a273df.png)

**Comment by Jigar3** [comment]
![screenshot_2018-01-12-00-19-17-260_com android chrome](https://user-images.githubusercontent.com/32068121/34841435-48f3640a-f72e-11e7-9739-3799bf517e90.png)

**Comment by Tachyon01** [comment]
![screenshot_20180112-002217](https://user-images.githubusercontent.com/34283302/34841623-de1eabfc-f72e-11e7-9343-28267616ec8a.png)

**Comment by DEVILCODER-SB99** [comment]
![screenshot 3](https://user-images.githubusercontent.com/33373098/34842004-2b5dc2f8-f730-11e7-874d-783506276d7f.png)

**Comment by adiagg2000** [comment]
![screenshot 32](https://user-images.githubusercontent.com/33027339/34842037-464fd88a-f730-11e7-9a28-a7fca0e2ea7e.png)

**Comment by abhishhh1** [comment]
![screenshot 5](https://user-images.githubusercontent.com/31480124/34843020-4ef08072-f733-11e7-9c38-6e5733aad8d8.png)

**Comment by Ace-Bansal** [comment]
![screenshot_2018-01-12-01-04-16-189_com android chrome](https://user-images.githubusercontent.com/34866483/34843464-95c4f70c-f734-11e7-9901-d1f0765ed72c.png)

**Comment by swaager** [comment]
![screenshot from 2018-01-13 00-47-22](https://user-images.githubusercontent.com/29673845/34843662-175d1d1c-f735-11e7-8a85-95fd276891e5.png)

**Comment by gau1rav** [comment]
![starred](https://user-images.githubusercontent.com/34263673/34847028-081335e8-f740-11e7-903e-1f1fabc203f3.png)

**Comment by surasnayak** [comment]
Done
![screenshot from 2018-01-12 08-06-25](https://user-images.githubusercontent.com/21239888/34847485-7b8c22fe-f741-11e7-86bb-2890e0b9055f.png)

**Comment by cuz789** [comment]
![2018-01-12 2](https://user-images.githubusercontent.com/35086901/34849555-be4a901a-f748-11e7-8f37-8ef441c8372d.png)

**Comment by Tlazypanda** [comment]
![screenshot_2018-01-12-03-50-40](https://user-images.githubusercontent.com/33183263/34850434-ca7e3e56-f74b-11e7-96cd-df797f3aa2b9.png)

**Comment by vvvinamer** [comment]
![screenshot 33](https://user-images.githubusercontent.com/35339278/34868720-ba2bd9be-f7aa-11e7-96ec-b1fb4666493d.png)

**Comment by ShiningSaurabh** [comment]
![capture](https://user-images.githubusercontent.com/34839782/34869094-e2106a8e-f7ab-11e7-8a6f-097ecd45a5c1.PNG)

**Comment by prathamprakash29** [comment]
![image](https://user-images.githubusercontent.com/30841366/34869805-222030ee-f7ae-11e7-94a9-90bce6eb9dbc.png)

**Comment by AlphaCholera** [comment]
![screenshot from 2018-01-12 21-12-57](https://user-images.githubusercontent.com/33174671/34870173-59e18270-f7af-11e7-8ad6-940d57c97ed1.png)

**Comment by aadixiiita** [comment]
![screenshot_20180112-182729](https://user-images.githubusercontent.com/34688457/34876179-78aaced4-f7c6-11e7-89cb-1d84b1272d1a.png)

**Comment by MaanasVohra** [comment]
![screen shot 2018-01-13 at 7 20 01 pm](https://user-images.githubusercontent.com/25277647/34906550-d4d1be50-f895-11e7-9402-80b79275459e.png)

**Comment by hacker1x1x1** [comment]
![image](https://user-images.githubusercontent.com/34509429/34907593-0d4ac476-f836-11e7-9c36-3bc31f0c6532.png)

**Comment by shivhek25** [comment]
![screen shot 2018-01-13 at 10 30 11 pm](https://user-images.githubusercontent.com/24766191/34908153-6cef40de-f8b1-11e7-8952-204e493eb843.png)

**Comment by anandwana001** [comment]
![screenshot_2018-01-14-03-35-55-580_com android chrome](https://user-images.githubusercontent.com/25057618/34910454-0dd467de-f8dc-11e7-8ceb-ce432e5d6592.png)

**Comment by ashish4321** [comment]
![screen shot 2018-01-14 at 12 20 52](https://user-images.githubusercontent.com/25305613/34913501-75075ee0-f925-11e7-8c60-45174a9357bc.png)
